#version: '3.8'

services:
  model-scanner:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MODEL_SECURITY_CLIENT_ID=${MODEL_SECURITY_CLIENT_ID}
      - MODEL_SECURITY_CLIENT_SECRET=${MODEL_SECURITY_CLIENT_SECRET}
      - TSG_ID=${TSG_ID}
    volumes:
      - .:/app
