services:
  pan-model-scanner-ui:
    container_name: pan-model-scanner-ui
    build:
      context: .
      secrets:
        - id
        - secret
        - tsg
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env

secrets:
  id:
    file: ./id.txt
  secret:
    file: ./secret.txt
  tsg:
    file: ./tsg.txt
