apiVersion: v1
kind: Service
metadata:
  name: model-scanner-service
  namespace: model-scanner
spec:
  type: LoadBalancer
  selector:
    app: model-scanner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000