apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-scanner-deployment
  namespace: model-scanner
  labels:
    app: model-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-scanner
  template:
    metadata:
      labels:
        app: model-scanner
    spec:
      containers:
      - name: model-scanner
        image: jefrihillon/pan-model-scanner-ui:1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MODEL_SECURITY_CLIENT_ID
          value: "jef-model-scanner@1867591621.iam.panserviceaccount.com"
        - name: MODEL_SECURITY_CLIENT_SECRET
          value: "e8b7674a-a21e-483f-9cc1-89a4df47bcbc"
        - name: TSG_ID
          value: "1867591621"